#Text based RPG project by Joshua Harrison aka SeverX
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("Welcome to PLACEHOLDER, your journey is just beginning.")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
input("Press 'ENTER' to remember.....")                                         #For these empty inputs, they are there to require user interaction to continue the story. Should I just write them as "Press ENTER to continue...."?
print()                                                                         #In a CLI, those prompts will be blank space and may be very confusing to the user.


input("You wake up in a haze, unsure of where you are. The first question that comes to your mind is....")
char_name=input("What is your name? ")                                          #char_name will be the characters name throughout the game
print()

classchoice = True
class_list = ["Fighter","Wizard"]                                               #Master profession list
class_list_str=str(class_list)                                                  #Converted to string to be able to manipulate it for display
class_list_str=class_list_str.replace("'","")                                   #Remove ' from the converted list
class_list_l=[class_l.lower() for class_l in class_list]                        #Converted lowercase list for comparison to user input to avoid error <<<<<This code was generated by AI>>>>>


input(f"That's right.... {char_name}, but why are you here? What is your profession?")
print(f"Choose 1: {class_list_str[1:-1]}")                                      #Use converted class list to slice open and close brackets from output
  
import re

while classchoice == True:
  char_class=input("I am a ").lower()                                           #char_class will be the characters class throughout the whole game, converted to all lowercase for error avoidance in comparison
  char_class=re.sub(r'[^a-zA-Z]', '', char_class)                               #This module and code removes all non-alphabetical characters from input to avoid errors <<<<<This code was generated by AI>>>>>
  if class_list_l.count(char_class) != 1:
    print()
    print("~~~~You have chosen an incorrect profession, please try again.~~~~")
    print()
  else:
    classchoice = False
    print()
    print("Of course! You're a", char_class + "!")
    
